version: '3.8'

services:
  backend:
    build:
      context: ./  # Make sure this is set to the root of your project if 'backend' is under root
      dockerfile: backend/Dockerfile  # Specify Dockerfile location for the backend if needed
    ports:
      - "3001:3001"
    command: /bin/bash -c "npm i && node index.js"
    networks:
      - socialdroids_network

  frontend:
    build:
      context: ./  # Frontend is in the root directory
    ports:
      - "5173:5173"
    command: /bin/bash -c "npm i && npm run dev"
    networks:
      - socialdroids_network

networks:
  socialdroids_network:
    driver: bridge